---

- import_tasks: dependencies.yml

- name: ensure group is present
  group:
    name: "{{ userli_group }}"

- name: ensure user is present
  user:
    name: "{{ userli_user }}"
    group: "{{ userli_group }}"

- name: ensure userli sudoers file is present
  template:
    src: sudoers.d/userli.j2
    dest: /etc/sudoers.d/userli
    owner: root
    group: root
    mode: 0440

- name: download release
  get_url:
    url: "https://github.com/systemli/userli/releases/download/{{ userli_version }}/userli-{{ userli_version }}.tar.gz"
    dest: "{{ userli_home }}"
    owner: "{{ userli_user }}"
    group: "{{ userli_user }}"
    checksum: "sha512:{{ userli_sha512_checksum }}"
  register: userli_download
  when: not ansible_check_mode

# TODO: Check release tarball PGP signature

- name: make dir for release
  file:
    dest: "{{ userli_home }}/userli-{{ userli_version }}"
    state: directory
    owner: "{{ userli_user }}"
    group: "{{ userli_user }}"
    mode: 0755

# TODO: Chown app files as root:root for better security
#       Only var/cache and var/log should be owned by userli user
- name: unarchive release
  unarchive:
    src: "{{ userli_home }}/userli-{{ userli_version }}.tar.gz"
    dest: "{{ userli_home }}/userli-{{ userli_version }}"
    owner: "{{ userli_user }}"
    group: "{{ userli_user }}"
    remote_src: true
  when: userli_download.changed

- name: update permissions for release directory
  file:
    dest: "{{ userli_home }}/userli-{{ userli_version }}"
    state: directory
    owner: "{{ userli_user }}"
    group: "{{ userli_user }}"
    mode: 0755

- name: update permissions for documentroot
  file:
    dest: "{{ userli_home }}/userli-{{ userli_version }}/public"
    state: directory
    owner: "{{ userli_user }}"
    group: "{{ userli_user }}"
    mode: 0750

- name: ensure .env.local is installed
  template:
    src: ".env.local.j2"
    dest: "{{ userli_home }}/userli-{{ userli_version }}/.env.local"
    owner: "root"
    group: "userli"
    mode: 0640
  notify: dump environment for better performance

- name: ensure extra directories are latest
  file:
    dest: "{{ userli_home }}/userli-{{ userli_version }}/{{ item.path }}"
    state: directory
    owner: "{{ userli_user }}"
    group: "{{ userli_user }}"
    mode: 0755
  with_filetree: userli/
  when: item.state == 'directory'

- name: ensure extra files are latest
  copy:
    src: "{{ item.src }}"
    dest: "{{ userli_home }}/userli-{{ userli_version }}/{{ item.path }}"
    owner: "{{ userli_user }}"
    group: "{{ userli_user }}"
    mode: 0644
  with_filetree: userli/
  when: item.state == 'file'

- name: set link to current release
  file:
    state: link
    path: "{{ userli_symfony_path }}"
    src: "userli-{{ userli_version }}"

- import_tasks: primary.yml
  when: userli_primary

- name: ensure lograte config is latest
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/userli

- import_tasks: deployment.yml
  when: userli_update

- import_tasks: munin.yml
  when: userli_munin
  tags: munin
