---
- name: Preflight checks
  ansible.builtin.include_tasks: preflight.yml

- name: Ensure group is present
  ansible.builtin.group:
    name: "{{ userli_group }}"

- name: Ensure user is present
  ansible.builtin.user:
    name: "{{ userli_user }}"
    group: "{{ userli_group }}"

- name: Download release
  ansible.builtin.get_url:
    url: "https://github.com/systemli/userli/releases/download/{{ userli_version }}/userli-{{ userli_version }}.tar.gz"
    dest: "{{ userli_home }}"
    owner: "{{ userli_user }}"
    group: "{{ userli_user }}"
    checksum: "sha512:{{ userli_sha512_checksum[userli_version] }}"
    mode: "0644"
  register: userli_download
  when: not ansible_check_mode

# TODO: Check release tarball PGP signature
# TODO: Chown app files as root:root for better security
#       Only var/cache and var/log should be owned by userli user
- name: Unarchive release # noqa no-changed-when no-handler
  ansible.builtin.unarchive:
    src: "{{ userli_home }}/userli-{{ userli_version }}.tar.gz"
    dest: "{{ userli_home }}/"
    owner: "{{ userli_user }}"
    group: "{{ userli_user }}"
    remote_src: true
  when: userli_download.changed

- name: Update permissions for release directory
  ansible.builtin.file:
    dest: "{{ userli_home }}/userli-{{ userli_version }}"
    state: directory
    owner: "{{ userli_user }}"
    group: "{{ userli_user }}"
    mode: "0755"

- name: Update permissions for documentroot
  ansible.builtin.file:
    dest: "{{ userli_home }}/userli-{{ userli_version }}/public"
    state: directory
    owner: "{{ userli_user }}"
    group: "{{ userli_user }}"
    mode: "0750"

- name: Ensure .env.local is installed
  ansible.builtin.template:
    src: ".env.local.j2"
    dest: "{{ userli_home }}/userli-{{ userli_version }}/.env.local"
    owner: "{{ userli_user }}"
    group: "{{ userli_user }}"
    mode: "0640"
  notify: Dump environment for better performance

- name: Ensure extra directories are latest
  ansible.builtin.file:
    dest: "{{ userli_home }}/userli-{{ userli_version }}/{{ item.path }}"
    state: directory
    owner: "{{ userli_user }}"
    group: "{{ userli_user }}"
    mode: "0755"
  with_community.general.filetree: "{{ userli_directory }}"
  when: item.state == 'directory'

- name: Ensure extra files are latest
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "{{ userli_home }}/userli-{{ userli_version }}/{{ item.path }}"
    owner: "{{ userli_user }}"
    group: "{{ userli_user }}"
    mode: "0644"
  with_community.general.filetree: "{{ userli_directory }}"
  when: item.state == 'file'

- name: Set link to current release
  ansible.builtin.file:
    state: link
    path: "{{ userli_symfony_path }}"
    src: "userli-{{ userli_version }}"
  notify: Restart webserver

- name: Import tasks for DB primary
  ansible.builtin.import_tasks: primary.yml
  when: userli_primary | bool

- name: Ensure lograte config is latest
  ansible.builtin.template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.d/userli
    mode: "0644"

- name: Import deployment tasks
  ansible.builtin.import_tasks: deployment.yml
  when: userli_update | bool

- name: Import Munin tasks
  ansible.builtin.import_tasks: munin.yml
  when: userli_munin | bool

- name: Import metrics tasks
  import_tasks: metrics.yml
  when: userli_prometheus_textfile_collector_enabled | bool
