---

- name: restart munin-node
  service:
    name: munin-node
    state: restarted

- name: run composer dump-env prod
  command: composer dump-env prod
  args:
    chdir: "{{ userli_symfony_path }}"
  environment:
    APP_ENV: "prod"
  become_user: "{{ userli_user }}"
  ignore_errors: true
  listen: "dump environment for better performance"

- name: adjust permissions for dumped environment file
  file:
    dest: "{{ userli_home }}/userli-{{ userli_version }}/.env.local.php"
    owner: "{{ userli_user }}"
    group: "{{ userli_user }}"
    mode: 0640
  listen: "dump environment for better performance"
