---
driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: userli-buster64
    box: debian/buster64
    memory: 512
    cpus: 2
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 8080, host: 8080"

dependency:
  name: galaxy
  options:
    force: false

lint: yamllint .

provisioner:
  name: ansible
  become: true

# verifier:
#   name: goss
