---
driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: userli-bullseye64
    box: debian/bullseye64
    memory: 512
    cpus: 2
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 8080, host: 8080"

dependency:
  name: galaxy
  options:
    force: false
