---
scenario:
  name: default

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: userli-stretch64
    box: debian/stretch64
    memory: 512
    cpus: 2
    instance_raw_config_args:
      - "vm.network 'forwarded_port', guest: 80, host: 8080"

dependency:
  name: galaxy
  options:
    force: false

provisioner:
  name: ansible
  become: true
  lint:
    name: ansible-lint
    enabled: false

verifier:
  name: goss
  lint:
    name: yamllint
