---

- name: Install Caddy
  hosts: all
  become: true
  roles:
    - antoiner77.caddy
  vars:
    caddy_config: |
      :8080
      gzip
      root /var/www/userli/public
      # PHP-FPM Configuration
      fastcgi / /run/php/php7.1-fpm.sock php
    caddy_systemd_network_dependency: false
    caddy_systemd_restart_startlimitinterval: 10
  tasks:
    - file:
        path: /var/www/
        owner: www-data
        group: www-data
        mode: 0777
        state: directory

- name: Prepare
  hosts: all
  become: true
  roles:
    - manala.apt
    - manala.php
    - geerlingguy.mysql
  vars:
    manala_apt_repositories:
      - sury_php
    manala_apt_repositories_exclusive: false
    manala_apt_preferences:
      - php@sury_php
    manala_apt_packages:
      - acl  # support for unpriviledged become_user
      - git
      - make
      - postfix
      - unzip
      - zip
    manala_php_version: 7.1
    manala_php_extensions:
      # necessary
      - apcu
      - curl
      - gd
      - sodium
      - mbstring
      - mysql
      - xml
      - zip
      # performance
      - ctype
      - intl
      # debugging
      - xdebug
    manala_php_extensions_exclusive: false
    manala_php_sapis:
      - cli
      - fpm
    mysql_users:
      - name: userli
        password: userli
        priv: "userli.*:ALL"

- name: Install composer with php 7.1
  hosts: all
  become: true
  roles:
    - manala.apt
  vars:
    manala_apt_packages:
      - composer  # for composer dump-env
