---
- name: Prepare
  hosts: all
  become: true
  pre_tasks:
    - name: Run the equivalent of "apt-get update" before installing packages
      ansible.builtin.apt:
        update_cache: yes

    - name: Install cron for testing in docker containers
      ansible.builtin.apt:
        pkg: cron
  roles:
    - weareinteractive.apt
    - geerlingguy.apache
    - geerlingguy.php
    - systemli.mariadb
  vars:
    apache_listen_port: 8080
    apache_remove_default_vhost: true
    apache_vhosts:
      - servername: localhost
        documentroot: /var/www/userli/public
        extra_parameters: |
          SetEnv APP_ENV prod
    apt_packages:
      - acl # support for unpriviledged become_user
      - unzip
    php_packages:
      # necessary
      - libapache2-mod-php
      - php8.2-cli
      - php8.2-curl
      - php8.2-fpm
      - php8.2-gd
      - php8.2-mbstring
      - php8.2-mysql
      - php8.2-opcache
      - php8.2-xml
      - php8.2-zip
      # performance
      - php8.2-ctype
      - php8.2-intl
