---
- name: Prepare
  hosts: all
  become: true
  roles:
    - weareinteractive.apt
    - geerlingguy.apache
    - geerlingguy.php
    - systemli.mariadb
  vars:
    apache_listen_port: 8080
    apache_remove_default_vhost: true
    apache_vhosts:
      - servername: localhost
        documentroot: /var/www/userli/public
        extra_parameters: |
          SetEnv APP_ENV prod
    apt_packages:
      - acl  # support for unpriviledged become_user
      - unzip
    php_default_version_debian: 7.3
    php_packages:
      # necessary
      - libapache2-mod-php
      - php{{ php_default_version_debian }}-apcu
      - php{{ php_default_version_debian }}-cli
      - php{{ php_default_version_debian }}-curl
      - php{{ php_default_version_debian }}-fpm
      - php{{ php_default_version_debian }}-gd
      - php{{ php_default_version_debian }}-mbstring
      - php{{ php_default_version_debian }}-mysql
      - php{{ php_default_version_debian }}-xml
      - php{{ php_default_version_debian }}-zip
      # performance
      - php{{ php_default_version_debian }}-ctype
      - php{{ php_default_version_debian }}-intl
      # debugging
      - php{{ php_default_version_debian }}-xdebug
