---
- name: Prepare
  hosts: all
  become: true
  vars:
    packages:
      - acl  # support for unpriviledged become_user
      - cron
      - unzip
      # necessary
      - apache2
      - mariadb-server
      - libapache2-mod-php
      - php7.4-apcu
      - php7.4-cli
      - php7.4-curl
      - php7.4-fpm
      - php7.4-gd
      - php7.4-mbstring
      - php7.4-mysql
      - php7.4-xml
      - php7.4-zip
      # performance
      - php7.4-ctype
      - php7.4-intl
      # debugging
      - php7.4-xdebug
    apache_listen_port: 8080
    apache_remove_default_vhost: true
    apache_vhosts:
      - servername: localhost
        documentroot: /var/www/userli/public
        extra_parameters: |
          SetEnv APP_ENV prod
  tasks:
    - name: Install dependencies
      apt:
        pkg: "{{ packages }}"
        update_cache: yes

    - name: Start required services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
      loop:
        - apache2
        - mariadb
