---

- name: Install Caddy
  hosts: all
  become: true
  roles:
    - antoiner77.caddy
  vars:
    caddy_config: |
      :8080
      gzip
      root /var/www/userli/public
      # PHP-FPM Configuration
      fastcgi / /run/php/php7.3-fpm.sock php
      rewrite {
        to {path} /index.php?{query}
      }
    caddy_systemd_network_dependency: false
    caddy_systemd_restart_startlimitinterval: 10
    caddy_update: false
  tasks:
    - file:
        path: /var/www/
        owner: www-data
        group: www-data
        mode: 0777
        state: directory

- name: Prepare
  hosts: all
  become: true
  roles:
    - weareinteractive.apt
    - geerlingguy.php
    - mejo-.mariadb
  vars:
    apt_packages:
      - acl  # support for unpriviledged become_user
      - unzip
    php_default_version_debian: 7.3
    php_packages:
      # necessary
      - php{{ php_default_version_debian }}-apcu
      - php{{ php_default_version_debian }}-cli
      - php{{ php_default_version_debian }}-curl
      - php{{ php_default_version_debian }}-fpm
      - php{{ php_default_version_debian }}-gd
      - php{{ php_default_version_debian }}-mbstring
      - php{{ php_default_version_debian }}-mysql
      - php{{ php_default_version_debian }}-xml
      - php{{ php_default_version_debian }}-zip
      # performance
      - php{{ php_default_version_debian }}-ctype
      - php{{ php_default_version_debian }}-intl
      # debugging
      - php{{ php_default_version_debian }}-xdebug
    php_webserver_daemon: caddy
