---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml
    force: false

driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local

platforms:
  - name: localhost

provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: ../default/converge.yml
    verify: ../default/verify.yml
